# Generated by Django 4.1.5 on 2023-01-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AditGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=250, verbose_name='Краткий текст')),
                ('image', models.ImageField(upload_to='block/img/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=150, verbose_name='Краткий текст')),
                ('keywords', models.TextField(max_length=250, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=150, verbose_name='Краткий текст')),
                ('show_url', models.BooleanField(default=True)),
                ('slider_1', models.ImageField(upload_to='slider/img/', verbose_name='Изображение')),
                ('slider_2', models.ImageField(upload_to='slider/img/', verbose_name='Изображение')),
                ('slider_3', models.ImageField(upload_to='slider/img/', verbose_name='Изображение')),
                ('block_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.block')),
                ('seo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=150, verbose_name='Краткий текст')),
                ('show_url', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='slider/img/', verbose_name='Изображение')),
                ('files', models.FileField(upload_to='files/', verbose_name='Документы')),
                ('adit_header', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('adit_text', models.CharField(max_length=150, verbose_name='Краткий текст')),
                ('seo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.seo')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.service'),
        ),
    ]
