# Generated by Django 4.1.6 on 2023-02-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название документа')),
                ('files', models.FileField(upload_to='files/', verbose_name='PDF, JPG (макс. размер 20 Mb)')),
            ],
        ),
        migrations.RemoveField(
            model_name='aditgallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='block',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='files',
        ),
        migrations.RemoveField(
            model_name='info',
            name='seo_id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='show_url',
        ),
        migrations.RemoveField(
            model_name='main',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='main',
            name='seo_id',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_id',
        ),
        migrations.AddField(
            model_name='aditgallery',
            name='adit_image',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='block',
            name='main',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='site_app.main'),
        ),
        migrations.AddField(
            model_name='block',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_app.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='seo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='site_app.seo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='seo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='site_app.seo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seo',
            name='descriptions',
            field=models.CharField(default=1, max_length=200, verbose_name='Краткий текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seo',
            name='titles',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='seo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='site_app.seo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='block',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='info',
            name='adit_header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='info',
            name='adit_text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='info',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='info',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='main',
            name='header',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, max_length=200, null=True, verbose_name='Краткий текст')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на комерческий сайт')),
                ('map', models.CharField(blank=True, max_length=200, null=True, verbose_name='Код карты')),
                ('fio', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Локация')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='E-mail')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='site_app.seo')),
            ],
        ),
    ]
