# Generated by Django 4.1.6 on 2023-02-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_files_remove_aditgallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='main',
        ),
    ]
