# Generated by Django 4.1.6 on 2023-02-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AditGallery',
        ),
        migrations.RemoveField(
            model_name='block',
            name='service_id',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='info',
            name='seo_id',
        ),
        migrations.RemoveField(
            model_name='main',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='main',
            name='seo_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_id',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.DeleteModel(
            name='Seo',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
