# Generated by Django 4.1.6 on 2023-02-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
