# Generated by Django 4.1.6 on 2023-02-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_tariff_pricetariffservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetariffservices',
            name='tariff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='services_app.tariff'),
        ),
    ]
