# Generated by Django 4.1.6 on 2023-02-23 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_alter_house_image_1_alter_house_image_2_and_more'),
        ('services_app', '0004_alter_pricetariffservices_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('income_invoice', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='income', max_length=16, verbose_name='Приход/Расход')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название компании')),
                ('information', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True, verbose_name='Номер показания')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('accounted', 'Учтено'), ('paid', 'Учтено и оплачено'), ('zero', 'Нулевое')], default='new', max_length=16, verbose_name='Статус')),
                ('expense', models.IntegerField(verbose_name='Показания счетчика')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.apartment', verbose_name='Квартира')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_app.services', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Показание счетчика',
                'verbose_name_plural': 'Показания счетчика',
            },
        ),
    ]
