# Generated by Django 4.1.6 on 2023-02-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='has_apartment',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_application',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_cashbox',
            new_name='cashbox',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_house',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_invoice',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_meter',
            new_name='meter',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_personal_account',
            new_name='personal_account',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_requisites',
            new_name='requisites',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_site_management',
            new_name='site_management',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_statistics',
            new_name='statistics',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_tariff',
            new_name='tariff',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_users',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='role',
            name='has_role',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.BooleanField(default=False, verbose_name='Доступ к ролям'),
        ),
    ]
