# Generated by Django 4.1.6 on 2023-02-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_has_apartment_role_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='roles',
            field=models.CharField(blank=True, choices=[('director', 'Директор'), ('manager', 'Менеджер'), ('accountant', 'Бухгалтер'), ('electric', 'Электрик'), ('plumber', 'Сантехник')], default='director', max_length=16, verbose_name='Роль'),
        ),
    ]
