# Generated by Django 4.1.6 on 2023-02-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_role_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='rol',
        ),
    ]
