# Generated by Django 4.1.6 on 2023-02-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('services_app', '0004_alter_pricetariffservices_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 5')),
                ('floors', models.ManyToManyField(to='house_app.floor', verbose_name='Этажи')),
                ('sections', models.ManyToManyField(to='house_app.section', verbose_name='Секции')),
                ('users', models.ManyToManyField(to='user_app.userprofile', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер квартиры')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь (кв.м.)')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.floor', verbose_name='Этаж')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apartment', to='user_app.userprofile', verbose_name='Владелец')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.section', verbose_name='Секция')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services_app.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'unique_together': {('section', 'floor', 'number')},
            },
        ),
    ]
