# Generated by Django 4.1.6 on 2023-02-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='house/', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='house/', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='house/', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='house/', verbose_name='Изображение 4'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='house/', verbose_name='Изображение 5'),
        ),
    ]
