# Generated by Django 4.1.7 on 2023-03-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_alter_house_image_1_alter_house_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sections',
        ),
        migrations.AddField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.house'),
        ),
        migrations.AddField(
            model_name='floor',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house_app.house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house_app.house'),
            preserve_default=False,
        ),
    ]
