# Generated by Django 4.1.7 on 2023-03-20 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_rename_role_role_rol'),
        ('house_app', '0003_remove_house_floors_remove_house_sections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_work', 'В работе'), ('done', 'Выполнено')], default='new', max_length=7, verbose_name='Статус')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('comment', models.TextField(blank=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.apartment')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.userprofile')),
                ('type_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.role')),
            ],
        ),
    ]
