# Generated by Django 4.1.7 on 2023-03-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0004_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type_master',
            field=models.CharField(choices=[('any', 'Любой специалист'), ('electric', 'Электрик'), ('plumber', 'Сантехник')], default='any', max_length=16, verbose_name='Тип мастера'),
        ),
    ]
