# Generated by Django 4.1.7 on 2023-03-22 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0005_alter_request_type_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
