# Generated by Django 4.1.7 on 2023-04-03 15:16

from django.db import migrations, models
import django.db.models.deletion
import house_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=house_app.models.account_number, unique=True, verbose_name='Номер лицевого счета')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=16, verbose_name='Статус')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Остаток (грн.)')),
                ('apartment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_account', to='house_app.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Лицевой счет',
                'verbose_name_plural': 'Лицевые счета',
            },
        ),
    ]
