# Generated by Django 4.1.7 on 2023-04-07 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import house_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0005_item_requisite_meterreading'),
        ('site_app', '0003_remove_block_main'),
        ('house_app', '0008_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=house_app.models.invoice_number, unique=True, verbose_name='Номер квитанции')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('done', models.BooleanField(default=True, verbose_name='Проведена')),
                ('status', models.CharField(choices=[('paid', 'Оплачена'), ('piece', 'Частично оплачена'), ('unpaid', 'Неоплачена')], default='unpaid', max_length=16, verbose_name='Статус')),
                ('date_from', models.DateField(default=django.utils.timezone.now, verbose_name='Период с')),
                ('date_before', models.DateField(default=django.utils.timezone.now, verbose_name='Период до')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Сумма')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house_app.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Квитанция',
                'verbose_name_plural': 'Квитанции',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='house_app.apartment', verbose_name='Номером Квартиры'),
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_for_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за ед., грн.')),
                ('expense', models.IntegerField(verbose_name='Расход')),
                ('full_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость, грн.')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.invoice', verbose_name='Квитанция')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга для квитанции',
                'verbose_name_plural': 'Услуги для квитанций',
                'unique_together': {('invoice', 'service')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(through='house_app.InvoiceService', to='site_app.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services_app.tariff', verbose_name='Тариф'),
        ),
    ]
