# Generated by Django 4.1.7 on 2023-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0011_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='template', max_length=16, verbose_name='Шаблон')),
                ('type', models.BooleanField(default=False, verbose_name='Назначить шаблоном по умоланию')),
                ('file', models.FileField(upload_to='files', verbose_name='Шаблонь')),
            ],
        ),
    ]
